### ISSUE TITLE
Loop semantics aren't defined in the spec

### ISSUE THREAD

**Issue by Edgeworth** [ZacharyForman/Gozzlang-Comp#2]

**Comment by ZacharyForman** [comment]
Loop semantics are carefully defined, reread the language specification.

**Comment by Edgeworth** [comment]
Reread it, my current understanding of loops in gozzlang are: 1. all loops are infinite loops, 2. <Gozz can end any loop, so whether Gozz> Gozz> <Gozz <Gozz is (()) or ({)} is undefined.

**Comment by ZacharyForman** [comment]
Your interpretation of (1) and (2) are both correct. Your program must, as
the spec says, interpret Gozz> as ending *a* loop.

**Comment by Edgeworth** [comment]
I'm interested as to how you're going to verify an output is correct or not when loop matching is undefined. e.g.
Suppose a number means output it.
(1(2(3(4))))

Strings generated by this program are prefixed by 1234(1234|234|34|4|)*

**Comment by ZacharyForman** [comment]
You will only receive well defined Gozzlang programs.

**Comment by shasheene** [comment]
> Your interpretation of (1) and (2) are both correct. Your program must, as the spec says, interpret Gozz> as ending *a* loop.

I assume that was a typo and you meant <Gozz as ending a single loop.

By the way, prior to #7, my reading of the specification suggests all loops are NOT necessarily infinite loops. The specification allows branching with the Gozz/ operator, which allows flow control to break out of an iteration in the loop. Consider the following input:

```

Gozz: GozZ
  Gozz> Gozz? Gozz/  <Gozz Gozz!

10 8 7 6 4 2 GozZ Gozz$ Gozz$

```

An implementation (whose only state happened to be the stack, and the user-defined functions) that reads and executes each space delimited word individually will loop 3 times (popping 2, then 4, then 6) then return from the function and print 8 and 10, while still being in started loop (not jumping back until it executes a <Gozz at some point)

The specification clarification #7 prevents this situation.

That's my reading of it anyway. I might be wrong/misinterpreting things
